server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/shard?serverTimezone=GMT
    username: root
    password: 123456
logging:
  level:
    ROOT: warn
    com.iric: debug

ExceptionMsgBot:
  url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=bd650041-fbb2-4584-b048-79cc3a685b0c
  alarm: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=bd650041-fbb2-4584-b048-79cc3a685b0c